server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://node10:3306/openmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

openmall:
  log:
    file-path: /Users/yangxiaoyu/work/test/openmall/api/logs
    level: debug
  upload:
    image-user-face-location: /Users/yangxiaoyu/work/test/openmall/images/faces
    image-server-url: http://localhost:8088/faces