server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/openmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 生产环境不需要打印

openmall:
  upload:
    image-user-face-location: /openmall/images/faces
    image-server-url: http://192.168.1.20:8088/openmall-api/faces