server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://node100:3306/openmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  redis:
    host: node100
    password: openmall
    database: 0
    port: 6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 生产环境不需要打印

openmall:
  log:
    level: debug
  upload:
    image-user-face-location: /Users/yangxiaoyu/work/test/openmall/images/faces
    image-server-url: http://localhost:8088/faces