server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://node10:3306/openmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  redis:
    cluster:
      nodes: 192.168.1.10:6379,192.168.1.11:6379,192.168.1.12:6379,192.168.1.20:6379,192.168.1.21:6379,192.168.1.22:6379
    database: 0
    password: openmall

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 生产环境不需要打印

openmall:
  log:
    file-path: /openmall/install/openmall/api/logs
    level: debug
  upload:
    image-user-face-location: /openmall/images/faces
    image-server-url: http://node20:8088/faces