server:
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  application:
    name: openmall-cart-service
  profiles:
    active: dev # 激活环境配置，dev开发环境，test测试环境，prod生产环境
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为500kb
      max-request-size: 512000  # 请求大小限制为500kb

openmall:
  sid: 336b56d13f7744e98ebe4bca03f8aa40
  log:
    # 日志格式化输出
    # %d 日期
    # %thread 线程名
    # %-5level level从左显示5个字符宽度
    # %logger{50} Class的完全限定名称，数字表示限制字符长度
    # %msg 日志消息
    # %n 表示换行符
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%-5level] %logger{50} - %msg%n"
    # 日志文件保留天数
    max-history: 60
    # 日志文件最大文件大小
    max-file-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
    registry-fetch-interval-seconds: 3  # 默认30s刷新缓存