server:
  port: 8040  # 服务端口

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.80.8:3306/openmall_portlet?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  redis:
    host: 192.168.80.8
    password: rain
    database: 0
    port: 6379
  elasticsearch:
    rest:
      uris: http://192.168.80.8:9200

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 生产环境不需要打印

# 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'  # include: health, info, xxxx

# openmall配置
openmall:
  log:
    file-path: D:/data/openmall/logs/portlet
    level: debug
  upload:
    image-user-face-location: D:/data/openmall/images/faces
    image-server-url: http://localhost:8088/faces

# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
    registry-fetch-interval-seconds: 30  # 默认30s刷新缓存

# feign配置
feign:
  hystrix:
    enabled: true # feign开启hystrix功能

# hystrix配置
hystrix:
  command:
    default: # 全局超时配置
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 4000 # 超时时间
            interruptOnTimeout: true # 超时以后终止线程
            interruptOnFutureCancel: true # 取消以后终止线程
      fallback:
        enabled: true # 是否开启服务降级
      circuitBreaker:
        enabled: true # 是否开启熔断，默认开启
        forceOpen: false  # 是否强制开启熔断开关
        forceClosed: false  # 是否强制关闭熔断开关
        requestVolumeThreshold: 5 # 熔断的前提条件（请求的数量），在一定的时间窗口内，请求达到5个以后，才开始进行熔断判断
        errorThresholdPercentage: 50  # 超过50%的失败请求后，则熔断开关开启
        sleepWindowInMilliseconds: 15000  # 当熔断开启以后，经过多少秒再进入半开状态
      metrics:
        rollingStats:
          timeInMilliseconds: 20000 # 配置时间窗口