server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://192.168.80.8:3306/openmall_item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  redis:
    host: 192.168.80.8
    password: rain
    database: 0
    port: 6379
  elasticsearch:
    rest:
      uris: http://192.168.80.8:9200

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 生产环境不需要打印

# 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'  # include: health, info, xxxx
  security:
    enabled: false

openmall:
  log:
    file-path: D:/data/openmall/logs/item
    level: debug
  upload:
    image-user-face-location: D:/data/openmall/images/faces
    image-server-url: http://localhost:8088/faces